# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb0afa7f9fe017187a8559348d7e7aa16b2ffd490430091cd2423ab3ab6cef3aaecc5c412ba9a4a1a0c174105a1af6e15bfe2a7e89d670ac1098ee7c9c298911

test:
  secret_key_base: 1cd36b80c47e3c34d82e6e7ea37998e03cfb699acaddbc0ee7e24c7db76c041545c2c4e6b626cc060491a5b18bdf5207a1515276e9c53c76c350f0d5faceb5f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
